version: '3.3'
services:
  env-app:
    image: order-management:latest
    restart: on-failure
    volumes:
      - ./target/order-management-0.0.1-SNAPSHOT.jar:/app/app.jar
    ports:
      - "5000:8080"
    environment:
      API_PORT: 8080
      API_VERSION: 1
      POSTGRESQL_URI: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: abc13579
