server:
  port: ${API_PORT:4000}
  servlet:
    context-path: ${SERVICE_PATH:/api/v0}

spring:
  profiles:
    active: ${ENV:local}

  application:
    name: order-management-service
    version: ${VERSION:0.0.1}
    auth-token-header:
      name: ${HEADER_KEY:Authorization}
    auth-token: ${API_KEY:fdasrv34atdzbt4zeex7y}

  datasource:
    url: ${POSTGRESQL_URI:jdbc:postgresql://localhost:5432/order_management?currentSchema=public}
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:abc13579}
    hikari:
      maximum-pool-size: ${HIKARI_POOL_SIZE:50}
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  #    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: ${MAX_UPLOAD_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:100MB}

security:
  path-matcher:
    permit-all-path-patterns:
      - /v0/api-docs/**
      - /v2/api-docs
      - /v2/api-docs/**
      - /v3/api-docs/**
      - /swagger-resources
      - /swagger-resources/**
      - /webjars/**
      - /swagger-ui.html
      - /swagger-ui/**

  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000 # 1 week duration by default: 1h * 60 minutes * 60 seconds * 1000 miliseconds

management:
  health:
    defaults:
      enabled: false
  endpoints:
    enabled-by-default: false
    health:
      enabled: false
    web:
      exposure:
        include: [ ]
      cors:
        allowed-origins: ${CORS_ORIGINS:*}
        allowed-methods: ${CORS_METHODS:*}
        allowed-headers: ${CORS_HEADERS:*}
        allow-credentials: ${CORS_CREDENTIALS:false}
  endpoint:
    info:
      enabled: false

gcp:
  server: ${GCP_SERVER_URL:http://localhost}
  port: ":4443"
  project:
    id: ${GCP_PROJECT_ID:order-management}
  bucket:
    id: ${GCP_BUCKET_ID:order-management}

telegram-bot:
  token: "6373709530:AAFYS5ZqiL3pjlGI-gr03-JSCOFNwwNdnuE"
  username: "lux_bot"
  group-id: -1002006995047

qr-code:
  with: 200
  height: 200

